# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [ published ]
  push:
    tags:
      - 'v*'  # ‰ªÖÂú®Ê†áÁ≠æÂåπÈÖç 'v*' Ê®°ÂºèÊó∂Ëß¶Âèë

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: üêº Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

        # Runs a single command using the runners shell
      - name: üî• publishing surgery-helper
        run: |
          chmod +x gradlew
          ./gradlew :surgery-helper:publishSurgeryPublicationToGithubPackagesRepository
        env:
          GITHUB_USER: ${{ secrets.NAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

        # Runs a single command using the runners shell
      - name: üî• publishing surgery-api
        run: |
          chmod +x gradlew
          ./gradlew :surgery-api:publishSurgeryPublicationToGithubPackagesRepository
        env:
          GITHUB_USER: ${{ secrets.NAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: üî• publishing surgery-doctor-arouter
        run: |
          chmod +x gradlew
          ./gradlew :surgery-doctor-arouter:publishSurgeryPublicationToGithubPackagesRepository
        env:
          GITHUB_USER: ${{ secrets.NAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: üî• publishing surgery-doctor-tryfinally
        run: |
          chmod +x gradlew
          ./gradlew :surgery-doctor-tryfinally:publishSurgeryPublicationToGithubPackagesRepository
        env:
          GITHUB_USER: ${{ secrets.NAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: üî• publishing surgery-doctors
        run: |
          chmod +x gradlew
          ./gradlew :surgery-doctors:publishSurgeryPublicationToGithubPackagesRepository
        env:
          GITHUB_USER: ${{ secrets.NAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - run: echo "üéâ The job finish publish all succeed."